[config]
broker = '127.0.0.1'
port = 1883
name = 'Moondalup City Square Parking'
location = 'Moondalup City Square Parking'
total-spaces = 192
total-cars = 0
topic-root = 'JS test-root'
topic-qualifier = 'JS test-qualifer'
